Added towny support
J3fftw1/HeadLimiter pull request #10
Opened 2021-12-05 21:55 UTC by Sfiguz7

As discussed in DMs, this is a QoL addition to give servers some extra protection against players trying to steal by making it impossible to place cargo nodes outside of towns, so that nobody can "extend" an existing cargo network and leech off of it.

2021-12-05 21:56 UTC, J3fftw1 approved these changes
LGTM @WalshyDev what do you think?

2021-12-05 22:01 UTC, WalshyDev requested changes

2021-12-05 22:01 UTC, WalshyDev commented on src/main/java/dev/j3fftw/headlimiter/Utils.java
> +        boolean isTownyWilderness = Bukkit.getServer().getPluginManager().isPluginEnabled("Towny")
We should have some util class. This is not fun and being expanded in the future isn't possible in a non-cancer way

2021-12-05 22:07 UTC, Sfiguz7 commented on src/main/java/dev/j3fftw/headlimiter/Utils.java
> +        boolean isTownyWilderness = Bukkit.getServer().getPluginManager().isPluginEnabled("Towny")
Do you mean Utils.java? 😂 
I can create a `isPlacingAllowed` method or something which would return the && chain of all booleans you may want to add in the future if that's more like what you want

2021-12-06 09:44 UTC, J3fftw1 commented on src/main/java/dev/j3fftw/headlimiter/Utils.java
> +        boolean isTownyWilderness = Bukkit.getServer().getPluginManager().isPluginEnabled("Towny")
Yea that would be nice.
We want to expand most stuff anyways so an Utils class would be nice and a method for other people to add their shit to would be really nice

2021-12-06 12:38 UTC, J3fftw1 requested changes

2021-12-06 12:38 UTC, J3fftw1 commented on src/main/java/dev/j3fftw/headlimiter/Utils.java
> +        return isTownyWilderness;
Since this is for expand ability  we might want to rename the boolean here

2021-12-06 12:38 UTC, J3fftw1 commented on src/main/java/dev/j3fftw/headlimiter/Utils.java
> +        // This is intentionally redundant to allow for expandability by adding more booleans and returning their || chain
```suggestion
        // This is intentionally redundant to allow for expand ability by adding more booleans and returning their || chain
```
I found this when i was typing the other comment apparently its typed like that

2021-12-06 12:38 UTC, J3fftw1 commented on src/main/resources/config.yml
> +block-towny-wilderness-cargo: false
Mind adding a protection "group" so if any other protection plugin needs to be added we dont have a million and 1 setting just in the "root" of the file

Not sure what these names are thats why " "

2021-12-06 12:50 UTC, J3fftw1 commented on src/main/java/dev/j3fftw/headlimiter/Utils.java
> +                player.sendMessage(ChatColor.RED + "You can't place Cargo nodes in unprotected areas!");
```suggestion
                player.sendMessage(ChatColor.RED + "You can't place Cargo nodes in unclaimed areas!");
```
This might be a better name but thats up to you @Sfiguz7

2021-12-06 12:53 UTC, Sfiguz7 commented on src/main/java/dev/j3fftw/headlimiter/Utils.java
> +        return isTownyWilderness;
Um which one? The return is supposed to be something like `isTownyWilderness || isGriefPreventionWilderness || isBlobNotHappy` etc etc

2021-12-06 12:56 UTC, J3fftw1 commented on src/main/java/dev/j3fftw/headlimiter/Utils.java
> +        return isTownyWilderness;
ah okay nvm then

2021-12-06 18:46 UTC, merged